services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Application
    App\Character\Application\Command\:
        resource: '../../../Application/Command'
    App\Character\Application\Event\:
        resource: '../../../Application/Event'
    App\Character\Application\Query\:
        resource: '../../../Application/Query'

    # Infrastructure
    App\Character\Domain\CharacterRepository:
        class: App\Character\Infrastructure\Doctrine\Repository\CharacterRepository
    App\Character\Domain\ReadModel\CharacterRepository:
        class: App\Character\Infrastructure\Doctrine\Repository\ReadModel\CharacterRepository

    # UI
    App\Character\Ui\Controller\:
        resource: '../../../Ui/Controller'
        tags: ['controller.service_arguments']