services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Infrastructure
    App\Character\Domain\CharacterRepository:
        class: App\Character\Infrastructure\Doctrine\Repository\CharacterRepository
    App\Character\Domain\ReadModel\CharacterRepository:
        class: App\Character\Infrastructure\Doctrine\Repository\ReadModel\CharacterRepository

    # UI
    App\Character\Ui\Controller\:
        resource: '../../../Ui/Controller'
        tags: ['controller.service_arguments']