version: '3.7'

services:
  web:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src:/src:ro
      - ./infra/web/default.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      DB_HOST: db:3306
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres

  php:
    build: infra/php
    restart: always
    volumes:
      - ./src:/src:ro

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres