version: '3.7'

services:
  web:
    depends_on:
      - db
    build: infra/web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html/
      - ./infra/web/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      DB_HOST: db:3306
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres