doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            uuid: App\Character\Infrastructure\Doctrine\Types\UuidType
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: false
                connection: default
                mappings:
                    Character:
                        type: xml
                        dir: '%kernel.project_dir%/src/Character/Infrastructure/Doctrine/Mapping'
                        prefix: 'App\Character\Domain'
            readmodel:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: false
                connection: default
                mappings:
                    Character:
                        type: xml
                        dir: '%kernel.project_dir%/src/Character/Infrastructure/Doctrine/Mapping/ReadModel'
                        prefix: 'App\Character\Domain\ReadModel'

