services:
    App\Common\DDD\CommandBus:
        factory: ['App\Service\CommandBusFactory','build']
        arguments:
            - !tagged ddd.command_handler
            - '@logger'
            - '@doctrine'
            - '@app.event_bus'

    app.event_bus:
        class: App\Common\DDD\EventBus
        factory: ['App\Service\EventBusFactory','build']
        arguments: [!tagged ddd.event_handler]


    App\Common\DDD\QueryBus:
        factory: ['App\Service\QueryBusFactory','build']
        arguments:
            - !tagged ddd.query_handler
            - '@cache.app'
