# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # BUS
    App\Common\DDD\QueryBus: '@app.query_bus'
    App\Common\DDD\CommandBus: '@app.command_bus'

    app.query_bus:
        class: App\Common\DDD\QueryBus
        factory: ['App\Service\QueryBusFactory','build']
        arguments:
            - !tagged ddd.query_handler
            - '@cache.app'
    app.command_bus:
        class: App\Common\DDD\CommandBus
        factory: ['App\Service\CommandBusFactory','build']
        arguments:
            - !tagged ddd.command_handler
            - '@logger'
            - '@doctrine'
            - '@app.event_bus'
    app.event_bus:
        class: App\Common\DDD\EventBus
        factory: ['App\Service\EventBusFactory','build']
        arguments: [!tagged ddd.event_handler]

    # Application
    App\:
        resource: '../src/*/Application/**'

    _instanceof:
        App\Common\DDD\CommandHandler:
            tags: ['ddd.command_handler']
        App\Common\DDD\QueryHandler:
            tags: ['ddd.query_handler']
        App\Common\DDD\EventHandler:
            tags: ['ddd.event_handler']

imports:
    - { resource: "../src/Character/Infrastructure/Symfony/config/services.yaml"}
