name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build the stack
        run: docker-compose up -d && docker exec web bin/console c:c
